language: objective-c
osx_image: xcode8
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=DOButton.xcworkspace
  - IOS_FRAMEWORK_SCHEME="DOButton"
  - IOS_SDK=iphonesimulator10.0
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6S"   SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=10.0,name=iPhone 5"    SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK" BUILD_EXAMPLE="YES"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
